import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { JetBrains_Mono } from 'next/font/google';
import "./globals.css";
import { ThemeWrapper } from '@/components/theme/theme-wrapper';
import { Footer } from '@/components/footer';
import { ThemeToggle } from '@/components/theme/theme-toggle';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} font-mono antialiased`}
      >
        <ThemeWrapper>
          <div className="px-4 py-8">
            <div className="max-w-screen-md mx-auto min-h-dvh">
              <div className="flex justify-end mb-8">
                <ThemeToggle />
              </div>
              {children}
            </div>
          </div>
          <Footer />
        </ThemeWrapper>
      </body>
    </html>
  );
}
